name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

  # Allow running manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: false

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://manhtran01:$HF_TOKEN@huggingface.co/spaces/manhtran01/Chatbot_with_Tools main
